// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Models
{
    public partial class Applicant
    {
        public Applicant()
        {
            Skills = new HashSet<Skill>();
        }

        public int ApplicantId { get; set; }
        public byte[] ApplicantImg { get; set; }
        public string Name { get; set; }
        public string PhoneNo { get; set; }
        public string Email { get; set; }
        public int? Catagory { get; set; }
        public string Cv { get; set; }

        public virtual Catagory CatagoryNavigation { get; set; }

        public virtual ICollection<Skill> Skills { get; set; }
    }
}