// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Models
{
    public partial class Catagory
    {
        public Catagory()
        {
            Applicants = new HashSet<Applicant>();
            Employees = new HashSet<Employee>();
        }

        public int CatagoryId { get; set; }
        public string CatagoryName { get; set; }

        public virtual ICollection<Applicant> Applicants { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}