// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Models
{
    public partial class MonthlyAttendance
    {
        public int EmployeeId { get; set; }
        public int? Month { get; set; }
        public int? Year { get; set; }
        public int? NoOfHoursWorked { get; set; }
        public int? DaysPresent { get; set; }
        public int? Leaves { get; set; }
    }
}